Several changes, the blkid call will be done in the script itself and not in the rule, so that media-automount now only needs the device name as parameter, which is nice for using it from the terminal too if needed.

diff --git a/media-automount b/media-automount
--- a/media-automount
+++ b/media-automount
@@ -1,5 +1,5 @@
-#!/bin/bash
-#$1 = <action>/<dev>/<type>/<label>
+#!/bin/sh
+#$1 = <dev>
 
 # Directory to use for mounting the devices
 mdir=/media/
@@ -16,15 +16,54 @@ log() {
     logger -st "media-automount" "$*"
 }
 
-# clean
-for dir in "$mdir"/*; do
-    mountpoint -q "$dir" || rmdir "$dir"
-done
+if ! [ "$1" ]
+then
+    log "missing arguments! a device name must be provided"
+    exit 1
+else
+    dev=/dev/$1  
+fi
 
-IFS=/ read -r action dev type label <<<"$1"
-dir="${mdir}/${label:-$dev}.$type"
+# Check if the device exists, if not but mounted, umount it
+if ! [ -b $dev ]
+then
+    if grep /etc/mtab -qe "^$dev"
+    then
+	log "$dev device removed, umounting and cleaning /media"
+	if umount "$dev"
+	then
+	    exitcode=0
+	else
+	    log "Error umounting $dev errcode:$?"
+	    exitcode=$?
+	fi
+    else
+	log "device doesn't exist anymore or is not a block device: $dev"
+	exitcode=1
+    fi
 
-case $type in
+    # cleanup
+    for dir in "$mdir"/*
+    do
+	[ -d "$dir" ] && ! mountpoint -q "$dir" && rmdir "$dir"
+    done
+    exit $exitcode
+fi
+
+# Load additional info for the block device
+eval $(blkid -po export $dev)
+
+# Don't manage devices that are already in fstab
+if grep /etc/fstab -q -e "^[ \t]*$dev[ \t]" -e "${UUID}" -e "${LABEL}"
+then
+    log "$dev already in /etc/fstab, automount won't manage this entry"
+    #exit 1
+fi
+
+# directory name
+dir="${mdir}/${LABEL:-$dev}.$TYPE"
+
+case $TYPE in
     vfat)
 	mopts="$mopts,flush,gid=100,dmask=000,fmask=111"
 	;;
@@ -37,46 +76,18 @@ case $type in
 	;;
 esac
 
+log "mounting device $dev in $dir"
+mkdir -p "$dir"
+if mount -t "${mtype:-auto}" -o "$mopts" "$dev" "$dir"
+then
+    # Notify
+    username="$(ps au | awk '$11 ~ /^xinit/ { print $1; exit }')"
+    [[ "$username" ]] && DISPLAY=:0 runuser -u "$username" xdg-open "$dir"
+    log "Device successfully mounted: $dir"
+    exit 0
+else
+    log "Mount error: $?"
+    rmdir "$dir"
+    exit 1
+fi
 
-case $action in
-
-    mount)
-	# Don't automount devices that are already in fstab (unless they use 'noauto')
-	if grep /etc/fstab -e "^[ \t]*/dev/$dev[ \t]" | grep -qv 'noauto'
-	then
-	    log "device $dev is already in fstab with 'auto' option, the media-automount service won't manage this entry"
-	    exit 1
-	fi
-	
-	log "mounting device $dev in $dir"
-	mkdir -p "$dir"
-	if mount -t "${mtype:-auto}" -o "$mopts" "/dev/$dev" "$dir"
-	then
-	    # Notify
-	    username="$(ps au | awk '$11 ~ /^xinit/ { print $1; exit }')"
-	    [[ "$username" ]] && DISPLAY=:0 runuser -u "$username" xdg-open "$dir"
-	    log "Device successfully mounted: $dir"
-	    exit 0
-	else
-	    log "Mount error: $?"
-	    rmdir "$dir"
-	    exit 1
-	fi
-	;;
-
-    umount)
-	log "Umounting device $dev from $dir"
-	if [ -d "$dir" ]
-	then
-	    umount "$dir" && rmdir "$dir"
-	else
-	    log "Missing directory: $dir"
-	    exit 1
-	fi
-	;;
-
-    *)
-	log "Wrong parameters! action/dev/type/label = '$1'"
-	exit 1
-	;;
-esac
